Submit an event when a new record is stored
m-vo/contao-survey pull request #42
Opened 2021-03-17 09:22 UTC by dmolineus

This pull request adds a new event that is triggered when a new record is stored. It enables custom actions being triggered after that.

2021-03-17 13:30 UTC, m-vo requested changes

2021-03-17 13:30 UTC, m-vo commented
Nice! I was thinking about implementing an event as well for the same reasons. :+1:

2021-03-17 14:00 UTC, dmolineus commented on src/Event/SurveyRecordStoredEvent.php
> +final class SurveyRecordStoredEvent
I prefer `SurveySubmittedEvent` then. Using a custom listener for storing the record sounds reasonable if only a mail or API should be triggered.

2021-03-18 09:49 UTC, dmolineus commented
I renamed the event to `SurveySubmittedEvent`, moved the storing to a listener and also added an option to disable storing the records.

2021-03-18 10:28 UTC, m-vo requested changes
Small nitpicks but overall looks very promising! 
Thanks for your work, @dmolineus  :heart:

2021-03-18 10:28 UTC, m-vo commented on src/Resources/contao/dca/tl_survey.php
> +                    'tl_class' => 'w50 m12',
Should this get a clear as well? So that it always stays in the line even if `frozen` is removed from the palette?
```suggestion
                    'tl_class' => 'clr w50 m12',
```

2021-03-18 10:28 UTC, m-vo commented on src/Resources/contao/dca/tl_survey.php
> +                'sql' => ['type' => 'boolean', 'default' => false],
default value should match `default` from DCA definition

```suggestion
                'sql' => ['type' => 'boolean', 'default' => true],
```

2021-03-18 10:28 UTC, m-vo commented on src/Resources/views/Backend/survey_record.html.twig
> +        {% if store_records or count > 0 %}
If we're hiding this for `count == 0` we should probably also remove the first part from the message (`records.count`):
> '{0}No results|{1}1 result|[2, +Inf[%count% results'

2021-03-18 10:28 UTC, m-vo commented on src/Resources/config/services.yaml
> +      - { name: 'kernel.event_listener', event: 'Mvo\ContaoSurvey\Event\SurveySubmittedEvent', priority: 128 }
Is there a reason for the high priority? Why not 0 or `-128` by default so that storing is run late?

I guess you would e.g. want to make changes to the record before storing but send notifications later on.

2021-03-18 10:32 UTC, dmolineus commented on src/Resources/views/Backend/survey_record.html.twig
> +        {% if store_records or count > 0 %}
I think it's useful to see the no results message if I have enabled store records. So I don't want to hide it. The condition is meant for the case that storing is disabled but some records were stored before.

2021-03-18 10:35 UTC, dmolineus commented on src/Resources/config/services.yaml
> +      - { name: 'kernel.event_listener', event: 'Mvo\ContaoSurvey\Event\SurveySubmittedEvent', priority: 128 }
I thought it should be stored first before any other listener are executed. But I don't mind to change it.

2021-03-18 10:39 UTC, m-vo commented on src/Resources/views/Backend/survey_record.html.twig
> +        {% if store_records or count > 0 %}
Misread the core and got it now! :+1:

2021-03-18 10:42 UTC, m-vo commented on src/Resources/config/services.yaml
> +      - { name: 'kernel.event_listener', event: 'Mvo\ContaoSurvey\Event\SurveySubmittedEvent', priority: 128 }
Let's leave it as it is. It's probably best to define an explicit priority if you want adjust things anyway and the other use cases would just work then.

2021-03-18 10:42 UTC, m-vo approved these changes

2021-03-18 10:43 UTC, merged

2021-03-18 10:43 UTC, m-vo commented
Thank you @dmolineus.