Avoid too long names
m-vo/contao-survey pull request #48
Opened 2021-06-24 10:06 UTC by dmolineus

This fix handles the case for too long autogenerated names. The issue is caused by a too short name field (50 chars vs. 255 chars of the question field). To avoid the issue this fix does:

1. increase the length of the name field
2. check if the generated name would be longer than the database field

@m-vo Would you mind to increase the visible length of the `name` and `question` field? I would add it to the PR so.

/cc @frontendschlampe

2021-06-24 10:15 UTC, m-vo commented
> @m-vo Would you mind to increase the visible length of the name and question field? I would add it to the PR so.

Sounds sensible to me. :+1:

2021-06-24 11:10 UTC, dmolineus commented
> > @m-vo Would you mind to increase the visible length of the name and question field? I would add it to the PR so.
> 
> Sounds sensible to me.

Changes with ed5bd3d

2021-06-24 15:57 UTC, m-vo requested changes
Only one comment, looks good otherwise!

2021-06-24 15:57 UTC, m-vo commented on src/EventListener/DataContainer/SurveyQuestion.php
> +            // check if name would be too long
This does not seem to work IMHO as the length of the suffix isn't taken into account in the `substr`, see https://3v4l.org/FNKs4

What about just this?
```php
    // avoid collisions
    for ($suffix = 2; isNameAlreadyUsed($name); ++$suffix) {
        $name = substr($base, 0, $maxlength - \strlen((string) $suffix) - 1)."-$suffix";
    }
```

2021-06-28 09:05 UTC, dmolineus commented on src/EventListener/DataContainer/SurveyQuestion.php
> +            // check if name would be too long
Fine with me. I updated this pull request.

2021-06-28 09:05 UTC, m-vo approved these changes

2021-06-28 09:07 UTC, merged

2021-06-28 09:07 UTC, m-vo commented
Thank you @dmolineus.