Publish surveys
m-vo/contao-survey pull request #9
Opened 2021-01-14 13:27 UTC by dmolineus

This feature adds a published state to a survey and prevents editing of published surverys. Furthermore only published surveys are allowed to be used in the frontend. Publishing a survey will reset the records. A danger warning is shown in the backend.

2021-01-15 22:44 UTC, Total-Reality commented
Hi,
ist denn geplant die Erweiterung irgendwann in den Contao Manager zu packen? Wir wollten gerne mal etwas ausprobieren mit dem Survey, wir hatten vorher das hier eingesetzt:
https://packagist.org/packages/hschottm/contao-survey

Aber das geht irgendwie nicht mehr mit Contao 4.9

2021-01-16 15:56 UTC, m-vo commented
Rebased onto current master.

2021-01-16 15:59 UTC, m-vo commented
@Total-Reality Your comment doesn't have anything to do with this PR.

That said, there will be a 1.0.0 at some point in time but this is independent of the Contao Manager and the fact that the package is already available on packagist.

2021-01-16 16:13 UTC, Total-Reality commented
> @Total-Reality Your comment doesn't have anything to do with this PR.
> 
> That said, there will be a 1.0.0 at some point in time but this is independent of the Contao Manager and the fact that the package is already available on packagist.

Thats true, sorry, but in github is no possibility to send a message to you. 
Thank you for your answer.

2021-01-16 16:15 UTC, m-vo commented
No worries. Just open a new issue in these cases.

2021-01-16 16:34 UTC, Total-Reality commented
Thanks, good to know that this is the correct procedure.

2021-01-18 13:50 UTC, dmolineus commented
This PR is ready for review now. At the moment I use an internal flag `cleared` to indicate if a survey has cleared it's records when publishing it. We could make it more explicit by adding another checkbox `Clear records`. And only if no records exists, an unpublished survey may be published.

2021-01-19 09:39 UTC, m-vo requested changes

2021-01-19 09:39 UTC, m-vo commented on src/Entity/Survey.php
> +
Why do we need a second `cleared` property? 

Wouldn't this be enough:
```
shown in FR  <=> published
frozen in BE <=> published || #records > 0
```

Together with two actions: `publish` and `clear` where the first one just toggles the state and the other removes all records. Clearing of records is a feature that I wanted to implement anyway (e.g. because surveys were internally tested first and then reset again before being publicly released).

2021-01-19 09:39 UTC, m-vo commented on src/Entity/Survey.php
> +        $this->cleared = true;
Imo the owning side (`Record`) would need to be set to `null` as well.

2021-01-19 09:39 UTC, m-vo commented on src/EventListener/DataContainer/SurveySection.php
> +     * @Callback(table="tl_survey_section", target="config.onload")
Imo we should use a single method for all survey DCAs and just add multiple `@Callback` annotations. E.g. in `EventListener\DataContainer\Survey#freezeEditing`.

The onload callback will be called with a `DataContainer $dc` argument where we can use `$dc->table` to discriminate the table.

2021-01-19 09:39 UTC, m-vo commented on src/EventListener/DataContainer/SurveySection.php
> +        $survey = $this->surveyRepository->find(CURRENT_ID);
Could probably be `(int)$dc->id` instead of `CURRENT_ID`.

2021-01-19 09:49 UTC, dmolineus commented on src/EventListener/DataContainer/SurveySection.php
> +        $survey = $this->surveyRepository->find(CURRENT_ID);
But then I have to be aware of the current action of the `DC_Table`. The `$dc` unfortunately does not provide the information which action will be performed, so I have to check the `Input`. Sounds like yet another not ideal solution for me. But it's up to you.

2021-01-19 09:51 UTC, dmolineus commented on src/Entity/Survey.php
> +        $this->cleared = true;
Afaik this is done by `orphanRemoval` configuration, see https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/working-with-associations.html#orphan-removal

2021-01-19 09:53 UTC, dmolineus commented on src/Entity/Survey.php
> +
If we remove the "Contaoish" checkbox for publishing the survey you're right. We have to make sure however that a survey may only be published if the no records exists (otherwise we cannot guarantee that the existing records are valid with the changed configuration.

2021-01-19 09:55 UTC, dmolineus commented on src/EventListener/DataContainer/SurveySection.php
> +     * @Callback(table="tl_survey_section", target="config.onload")
Right now the callbacks differ a bit (Changing section title and description is allowed). If we remove it, I'm fine with using one listener for it.

2021-01-19 10:52 UTC, m-vo commented on src/Entity/Survey.php
> +
> We have to make sure however that a survey may only be published if the no records exists

What if we call the option sth. like `frozen` (or finalize) then? I think users shouldn't confuse this with publishing if there is more state involved. Think I'd assume I can just switch back and forth between published/unpublished without affecting anything.

What about this: 

```
frozen <=> 
  - shown in FE
  - edit of questions/sections disabled in BE

- freeze button toggles, but unfreeze only possible if there are no records
- clear button only available if records exist
```

Then a usual approach in the test phase would be: 
1. Create a survey with some sections + questions
2. Add a survey CTE (survey is not shown yet but a message that it's waiting to be frozen)
2. Freeze it
3. Test it
4. Happy with the results?
    - Yes: Clear records if there are any and you're done.
    - No: Proceed
5. Clear records if there are any + unfreeze
6. Adjust some things
7. Go back to 3

2021-01-19 10:58 UTC, m-vo commented on src/EventListener/DataContainer/SurveySection.php
> +        $survey = $this->surveyRepository->find(CURRENT_ID);
I think we should avoid the constants where possible. Not sure I get why it's needed in the first place, though. :smiley:  What's supposed to be in there? 

The core only uses this in very few places and takes the value from the session in newer code. Maybe we can do this as well? https://github.com/contao/contao/blob/bdba298d3f102bf119bdf178e1a7b6e902b90ffb/core-bundle/src/EventListener/Menu/BackendPreviewListener.php#L152-L160

2021-01-19 10:59 UTC, m-vo commented on src/EventListener/DataContainer/SurveySection.php
> +     * @Callback(table="tl_survey_section", target="config.onload")
Yeah let's look at this as the last step. :slightly_smiling_face:

2021-01-19 12:00 UTC, dmolineus commented on src/EventListener/DataContainer/SurveySection.php
> +        $survey = $this->surveyRepository->find(CURRENT_ID);
Yeah, I'll use this snippet as well. Haven't seen it before :-)

2021-01-19 12:02 UTC, dmolineus commented on src/Entity/Survey.php
> +
Agreed.

2021-02-03 11:38 UTC, m-vo commented
What's the state on this one? :slightly_smiling_face:

2021-02-03 12:15 UTC, dmolineus commented
> What's the state on this one?

Sorry, I had been sick for a few days so I lag behind on every project. I reworked the freezing so it's ready to get another review.

2021-02-03 17:00 UTC, m-vo commented
No worries whatsoever. :+1: 
I'll try to go over over this in the next day.

2021-02-08 11:18 UTC, m-vo requested changes

2021-02-08 11:18 UTC, m-vo commented on src/Resources/contao/dca/tl_survey.php
> +                'clearRecords' => [],
Wouldn't it be much simpler to point to the route directly?

```suggestion
                'clear_records' => [
                    'icon' => 'deleteAll.svg',
                    'route' => 'mvo_survey_clear_records'
                ],
```

 Then we would not need a a listener, a form type, an extra template and CSS adjustments :smiley:.

2021-02-08 11:43 UTC, dmolineus commented on src/Resources/contao/dca/tl_survey.php
> +                'clearRecords' => [],
But then you would have to use a GET request to trigger an action which you shouldn't do. ;-) If you don't care you can. :-)

2021-02-08 11:55 UTC, m-vo commented on src/Resources/contao/dca/tl_survey.php
> +                'clearRecords' => [],
Yes, I know and agree in general, but think we should ignore it, because that's how the whole BE now works and it's imo not worth the trouble. :upside_down_face:  

I'll put it on my list for the core, though. Maybe we can introduce a `method` button parameter in upcoming versions. So that you could do something like `'my_action' => ['route' => 'foo', 'method' => 'DELETE']`.

2021-03-01 14:52 UTC, dmolineus commented on src/Resources/contao/dca/tl_survey.php
> +                'clearRecords' => [],
Okay I reworked it with 
722253d so I hope all is fine now.

2021-03-03 09:43 UTC, merged

2021-03-03 09:44 UTC, m-vo commented
Thanks a lot @dmolineus :tada: